#ifndef BMX_DEVELOPER_SETTINGS_H
#define BMX_DEVELOPER_SETTINGS_H

#define BMX_DEVELOPER_PASSWORD_MAX_LEN 63U
#define BMX_API_PASSWORD_MAX_LEN 63U

#define BMX_DEVELOPER_LOG_BUFFER_MIN_KB 64U
#define BMX_DEVELOPER_LOG_BUFFER_STEP_KB 64U
#define BMX_DEVELOPER_LOG_BUFFER_DEFAULT_KB 64U
#define BMX_DEVELOPER_LOG_BUFFER_MAX_KB 1024U

#endif  // BMX_DEVELOPER_SETTINGS_H
